language: python
python:
  - "3.8"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  username: "__token__"
  password:
    secure: "WgptHO4RWLtD7UjJryOfmIliKLEgpzvJdTIJjGcnfr42C1TiJ4IumMLeD6WOeP5TvC+ogQTD+3SkJfKUyTClQBZyUwSCGdpWjXtlN+8otUFmpiTulJsXXDZyjsCjo5ZuJ4sBrnRaeARkeetPHAswrCBv8O+BMdMjenrD+QvcHGsJw7Tlts4gjolOIxbk+SDy45IHUUXFEr1jQRggOIERF6lQhfeLfn2Hj1pCafZPAtsfyM7ePo17l7VfHs/QHDqsk7FBeyaO84AlJyYmdpABSRWB8+VVnUAaRD8LkQkItI0R9bMF0VPGUld6H7R22cgt6XIyUo3ZkQcFLdvELqZs8H5GgyOOByVRP+APGZQ5l4/115MVPXXe8jLKrXp8MHqz5YBsz8ZUAQdznVUjOLAMamR6mcSKUbRNgJqDtlA1WjJQV7a8WJgsj0jzWqcy42jrzvSG834Gl0IiQORfk/DTb2jj/xzIE5c2SBIXmHsa+D6j9Cn6eqSxlP0gASQ4vbzlOINag8wx4IIFMRoScEHwr/cxh8G2TIx4YbZYm7rxlYfCJBqikSpCBMhSrYfYIwSOzHW3mKWkK+ASCPaO/YM2fc+NDyy5uskJ34cYF6pvII1UOZuT2nO7CIunNcs68qRF/A/JiOgYhA7OIhCXecZssCYHYMrdudHy8dJGQDwz7Uc="
  on:
    tags: true
